image: php:5.6-cli

before_script:
  - apt-get update -qq
  - apt-get install -y -qq git

phpunit tests:
  stage: test
  script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  # - php artisan key:generate
  - vendor/bin/phpunit tests
  allow_failure: true

deploy to heroku:
  stage: deploy
  script:
  - apt-get install -y ruby
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP_DEVELOP --api-key=$HEROKU_API_KEY