version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    depends_on:
      - database
    command: php -S web:8000 -t public
    restart: always
    networks:
      - web

  database:
    image: mysql:5.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_DATABASE: dbproject
    networks:
      - web
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin:5.1-apache
    depends_on: 
      - database
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=dbuser
      - PMA_PASSWORD=dbpassword
    networks:
      - phpmyadmin

networks:
  web:
  phpmyadmin:
